# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version_profile=1.21.11
supported_minecraft_version_profiles=1.21.11
candidate_minecraft_version_profiles=1.21.9-1.21.10

# Mod Properties
mod_version=2.6.3
maven_group=tempeststudios.inventorysort
archives_base_name=inventory-sort
