# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.fromEnv=JAVA_HOME,JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64

# Fabric Properties
minecraft_version_profile=1.21.11
supported_minecraft_version_profiles=1.20-1.20.4,1.20.5-1.20.6,1.21-1.21.5,1.21.6-1.21.8,1.21.9-1.21.10,1.21.11,26.x
candidate_minecraft_version_profiles=

# Mod Properties
mod_version=3.2.3
maven_group=tempeststudios.inventorysort
archives_base_name=inventory-sort

# Modrinth Project IDs
modrinth_inventorysort_project_id=V38RsqtI
modrinth_inventorysearch_project_id=wIOLlhbN
modrinth_inventorycatalogue_project_id=rV7fRk8Z
modrinth_fabric_api_project_id=P7dR8mSH
