pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'inventory-sort'

include 'inventorysort-core'
include 'inventorysort'
include 'inventorysearch'
include 'inventorycatalogue'

project(':inventorysort-core').projectDir = file('modules/inventorysort-core')
project(':inventorysort').projectDir = file('modules/inventorysort')
project(':inventorysearch').projectDir = file('modules/inventorysearch')
project(':inventorycatalogue').projectDir = file('modules/inventorycatalogue')
