base {
	archivesName = 'inventory-sort'
}

loom {
	mods {
		"inventorysort" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets {
	client {
		java {
			srcDir rootProject.file("src/client/java")
			include "tempeststudios/inventorysort/compat/sort/**"
			include "tempeststudios/inventorysort/InventorySortClient.java"
			include "tempeststudios/inventorysort/InventorySorter.java"
			include "tempeststudios/inventorysort/mixin/HandledScreenMixin.java"
		}
	}
}

dependencies {
	implementation rootProject.coreProjectDependency()
	include project(':inventorysort-core')
}
